# Generated by Django 2.2 on 2020-08-15 03:59

import apps.producto.models.producto
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.sobre_escribir_archivo
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Product Name')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Description')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoria',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Product Name')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Description')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrecioDetalle',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('monto', models.IntegerField(verbose_name='Amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Detailed Price',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrecioDivisa',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('coin', models.CharField(choices=[('USD', 'USD')], default='USD', max_length=2)),
                ('fecha_publicacion', models.DateTimeField(blank=True, editable=False, verbose_name='Coin price publication date')),
                ('monto', models.IntegerField(verbose_name='Amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Detailed Price',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrecioLote',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(blank=True, editable=False, verbose_name='Lot Price Publication Date')),
                ('archvo', models.TextField(blank=True, max_length=255, null=True, verbose_name='Lot Price File')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Lot Price',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PrecioDivisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(choices=[('USD', 'USD')], default='USD', max_length=2)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Coin price publication date')),
                ('monto', models.IntegerField(verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Detailed Price',
                'verbose_name_plural': 'Detailed Prices',
                'ordering': ['coin', 'fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=256, verbose_name='Product Code')),
                ('codigo_barra', models.CharField(max_length=256, verbose_name='Product Bar Code')),
                ('nombre', models.CharField(max_length=256, verbose_name='Product Name')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Description')),
                ('origen', models.CharField(choices=[('NACIONAL', 'NACIONAL'), ('IMPORTADO', 'IMPORTADO')], default='NACIONAL', max_length=2)),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Product Publication Date')),
                ('imagen', models.ImageField(blank=True, default='product/default.png', max_length=255, null=True, storage=helpers.sobre_escribir_archivo.SobreEscribirArchivo(), upload_to=apps.producto.models.producto.image_path_producto, verbose_name='Product Image')),
                ('categoria', models.ManyToManyField(blank=True, related_name='categorias', to='producto.Categoria', verbose_name='Product Category')),
                ('dominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_dominios', to='dominio.Dominio', verbose_name='Product Domain')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['dominio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Lot Price Publication Date')),
                ('archvo', models.FileField(blank=True, max_length=255, null=True, upload_to='precio/default.ods', verbose_name='Lot Price File')),
                ('dominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lote_precio_dominios', to='dominio.Dominio', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Lot Price',
                'verbose_name_plural': 'Lot Price',
                'ordering': ['dominio', 'fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='PrecioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(verbose_name='Amount')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_precio_lotes', to='producto.PrecioLote', verbose_name='Lot Price')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_precio_productos', to='producto.Producto', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Detailed Price',
                'verbose_name_plural': 'Detailed Prices',
                'ordering': ['lote__dominio', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(max_length=256, verbose_name='Product Code')),
                ('codigo_barra', models.CharField(max_length=256, verbose_name='Product Bar Code')),
                ('nombre', models.CharField(max_length=256, verbose_name='Product Name')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Description')),
                ('origen', models.CharField(choices=[('NACIONAL', 'NACIONAL'), ('IMPORTADO', 'IMPORTADO')], default='NACIONAL', max_length=2)),
                ('fecha_publicacion', models.DateField(blank=True, editable=False, verbose_name='Product Publication Date')),
                ('imagen', models.TextField(blank=True, default='product/default.png', max_length=255, null=True, verbose_name='Product Image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dominio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dominio.Dominio', verbose_name='Product Domain')),
            ],
            options={
                'verbose_name': 'historical Product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
