# Generated by Django 2.2 on 2020-08-14 13:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.sobre_escribir_archivo
import producto.models.producto


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=256, verbose_name='Product Name')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Description')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('uc', models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_categoria_uc', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_categoria_um', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(max_length=256, verbose_name='Product Code')),
                ('codigo_barra', models.CharField(max_length=256, verbose_name='Product Bar Code')),
                ('nombre', models.CharField(max_length=256, verbose_name='Product Name')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product Description')),
                ('origen', models.CharField(choices=[('NACIONAL', 'NACIONAL'), ('IMPORTADO', 'IMPORTADO')], default='NACIONAL', max_length=2)),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Product Publication Date')),
                ('imagen', models.ImageField(blank=True, default='product/default.png', max_length=255, null=True, storage=helpers.sobre_escribir_archivo.SobreEscribirArchivo(), upload_to=producto.models.producto.image_path_producto, verbose_name='Product Image')),
                ('categoria', models.ManyToManyField(blank=True, related_name='categorias', to='producto.Categoria', verbose_name='Product Category')),
                ('dominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_dominios', to='dominio.Dominio', verbose_name='Product Domain')),
                ('uc', models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_producto_uc', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_producto_um', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['dominio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Lot Price Publication Date')),
                ('archvo', models.FileField(blank=True, max_length=255, null=True, upload_to='precio/default.ods', verbose_name='Lot Price File')),
                ('dominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lote_precio_dominios', to='dominio.Dominio', verbose_name='Domain')),
                ('uc', models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_preciolote_uc', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_preciolote_um', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lot Price',
                'verbose_name_plural': 'Lot Price',
                'ordering': ['dominio', 'fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='PrecioDivisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('coin', models.CharField(choices=[('USD', 'USD')], default='USD', max_length=2)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Coin price publication date')),
                ('monto', models.IntegerField(verbose_name='Amount')),
                ('uc', models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_preciodivisa_uc', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_preciodivisa_um', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detailed Price',
                'verbose_name_plural': 'Detailed Prices',
                'ordering': ['coin', 'fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='PrecioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('monto', models.IntegerField(verbose_name='Amount')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_precio_lotes', to='producto.PrecioLote', verbose_name='Lot Price')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalle_precio_productos', to='producto.Producto', verbose_name='Product')),
                ('uc', models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_preciodetalle_uc', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producto_preciodetalle_um', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detailed Price',
                'verbose_name_plural': 'Detailed Prices',
                'ordering': ['lote__dominio', 'producto__nombre'],
            },
        ),
    ]
