# Generated by Django 2.2 on 2020-08-14 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191125_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpt',
            name='uc',
            field=models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_dpt_uc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dpt',
            name='um',
            field=models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_dpt_um', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glosary',
            name='uc',
            field=models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_glosary_uc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glosary',
            name='um',
            field=models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_glosary_um', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='uc',
            field=models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_sequence_uc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='um',
            field=models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_sequence_um', to=settings.AUTH_USER_MODEL),
        ),
    ]
