# Generated by Django 2.2 on 2020-08-14 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=256, verbose_name='Domain Name')),
                ('razon_social', models.CharField(max_length=256, verbose_name='Domain Business name')),
                ('uc', models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dominio_dominio_uc', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dominio_dominio_um', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['razon_social'],
            },
        ),
    ]
