# Generated by Django 2.2 on 2020-08-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Domain Name')),
                ('razon_social', models.CharField(max_length=256, verbose_name='Domain Business name')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['razon_social'],
            },
        ),
    ]
